### ISSUE TITLE
Multiple faces

### ISSUE THREAD

**Issue by Ng-Nic** [jeeliz/jeelizGlanceTracker#1]
Could you tell me if it is possible to fire an event for multiple faces detected? Also is it possible to integrate and object detection in the same stream?

- I have integrated glanceTracker into an Angular 7 project and it works great.

**Comment by xavierjs** [comment]
Hi,

GlanceTracker is a very minimalistic library, so multiface detection is not implemented.
You can use https://github.com/jeeliz/jeelizFaceFilter if you need multiface detection , with a light neuron network model (several are provided with the library) . You may need to increase the `animateDelay` initialization parameters to use fewer resources.

Object detection is not handled by GlanceTracker, but by this similar library: https://github.com/jeeliz/jeelizAR
We provide custom training services for object detection.

Best,
Xavier

**Comment by Ng-Nic** [comment]
thanks very much
