### ISSUE TITLE
GLANCETRACKERAPI.destroy() or stop()

### ISSUE THREAD

**Issue by santosh898** [jeeliz/jeelizGlanceTracker#2]
Thanks for the lightweight library.
It would be better if there is a method to stop the tracker completely and stopping the camera stream, cleaning the canvas.
something like `GLANCETRACKERAPI.destroy()`

**Comment by xavierjs** [comment]
Hi @santosh898 
I have added an option in the `toggle_pause` method, it can now shut down the camera video stream (so the camera light turns off).
I have updated the documentation and enabled this feature in the provided integration samples. You can check it out here: https://jeeliz.com/demos/glanceTracker/demos/integration/

```
GLANCETRACKERAPI.toggle_pause(true, true); --> pause and shut camera
GLANCETRACKERAPI.toggle_pause(false, true); --> resume and re-get camera
```

When the tracker is paused and camera turned off, nothing is running, no loop or whatever.
The memory footprint is neglictible.

Best,
Xavier
