### ISSUE TITLE
Model Source or Paper to cite

### ISSUE THREAD

**Issue by matteo-pennisi** [jeeliz/jeelizGlanceTracker#5]
Hi, thanks for this work.
It would be useful to add details about the model. If it's not yours could be interesting citing the original paper. Otherwise adding details about model implementation (data used for training, model, etc..) into readme.

Thanks

**Comment by xavierjs** [comment]
Hi,

These models are mine, and the training is fully done by my own proprietary toolchain.
I'm not particularly enthusiastic to see my models run on Google or Facebook DL frameworks, so I don't see why I would disclose them. In deep learning, even researchers are working for free for Google and Facebook by using and improving their tools...

Best,
Xavier
